        version: '3.8' # Or a version compatible with your docker compose install

        services:
          meds-backend:
            # Build the image using the Dockerfile in the current directory (.) of the cloned repo
            build: .
            container_name: meds-backend # Use the correct container name
            ports:
              # Map host port 3001 to container port 3001
              - "3001:3001"
            environment:
              # Port the app listens on inside the container
              - PORT=3001
              # Define your JWT Secret here. You can change this later via Portainer's Stack Editor.
              - JWT_SECRET=YOUR_INITIAL_STRONG_SECRET_KEY_HERE! # <-- SET YOUR SECRET KEY!
            restart: unless-stopped
            networks:
              - meds-network # Attach to its own network

        networks:
          meds-network: # Define the network for the meds backend
            driver: bridge

        
